### ISSUE TITLE
缺少了dragEnd 

### ISSUE THREAD

**Issue by lyxverycool** [m-Ryan/Project-R#12]
大佬，dragEnd 后没反应 应该去调用 addItem去更新list吧？我看好像注释掉了，去掉注释好像报错了

**Comment by m-Ryan** [comment]
> 大佬，dragEnd 后没反应 应该去调用 addItem去更新list吧？我看好像注释掉了，去掉注释好像报错了

今天才看到，上次用immer优化性能的时候写了一半忘记了，现在已经修复了。
